import "./globals.css";
import LoginForm from "@/components/LoginForm";

export const metadata = {
  title: "Home",
  desciotion: "Generated by Create Naext App",
};

export default function Home() {
  return (
    <>
      {/* mt-[450px] */}
      <div className=" items-center">
        <LoginForm />
      </div>
    </>
  );
}
